### PR TITLE
fixes #3 and #4

### LINKED ISSUE #3: Contents of file are read multiple times given the progression of position
In case of foundNewLine >= 0, the progression of position leads to multiple reads of the same data from the input file.

See line

https://github.com/neurosnap/gen-readlines/blob/master/index.js#L40

which will just add the length of the newline buffer, subsequently causing the rest of the read buffer to be discarded and read again in the next iteration.

Here is what I came up with to solve that problem

```
 35    let foundNewline = _foundNewline(readChunk);
 36     while (foundNewline >= 0)
 37     {
 38         let newlineBuffer = new Buffer(readChunk.slice(0, foundNewline));
 40         yield _concat(lineBuffer, newlineBuffer);
 42         readChunk = readChunk.slice(foundNewline+1);
 43         foundNewline = _foundNewline(readChunk);
 44     }
 45     position += bufferSize;
 46     lineBuffer = _concat(lineBuffer, readChunk);
 47  }
 48  // dump whatever...
```

I already applied your solution to the missing empty lines here.

### PR DESCRIPTION
**Pull request by silkentrance**
Please have a look at the code and tell me what needs to be changed.
I tried to optimize it as much as possible including also getting rid of duplicate code.

### CODE REVIEW

**Comment by silkentrance** [comment]
Shite, I changed the test cases for windos to use a buffersize of 1 and now they will fail :grin:, fixing now.

**Comment by silkentrance** [comment]
Test data for WINDOS new lines was converted using unix2dos and test cases use a buffer size of 1 to make sure that readline must detect whether it has seen a CR before and then skip the following LF.

**Comment by silkentrance** [comment]
Given the micro benchmark, I did run some tests and the fix will actually improve overall processing speed. I think, getting rid of the _concat function will further improve the performance.

```
line-reader
Benchmark took 81259529 nanoseconds                         (1)

gen-readlines w/o fix
w/ console output: Benchmark took 683679796 nanoseconds
w/o console output: Benchmark took 128673934 nanoseconds        (2)

gen-readlines with fix for #3 + #4
w/ console output: Benchmark took 181464649 nanoseconds
w/o console output: Benchmark took 85694172 nanoseconds         (3)

(1)  81259529
(2) 128673934
(3)  85694172

gen-readlines w/ fix comes close to line-reader and outperforms gen-readlines w/o the fix

however, when applying toString() to each line, that number (3) is increased to 92950941.
```

**Comment by silkentrance** [comment]
I have applied some more optimizations and now we are down to

Benchmark took 46636511 nanoseconds

which is half of the time line-reader takes.

**Comment by silkentrance** [comment]
I have tried various other "optimizations" but it seems that this is as best as it can get unless you or somebody else figures out a better way to do things. Getting rid of the _concat helper actually made things worse.

**Comment by silkentrance** [comment]
I added linebyline as yet another micro benchmark for comparison. Well, it seems that the ReadStream based version is even better than reading into buffers

Benchmark took 27591215 nanoseconds

**Comment by neurosnap** [comment]
Awesome job!  I'll publish to npm.

**Pull request merged**
